# Generated by Django 4.2.1 on 2023-05-24 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50, verbose_name='Title 1')),
                ('title2', models.CharField(max_length=50, verbose_name='Title 2')),
                ('price_title', models.CharField(max_length=50, verbose_name='Price Title')),
                ('del_btn', models.CharField(max_length=40, verbose_name='Delete Button')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
            ],
        ),
        migrations.CreateModel(
            name='ContactContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtitle')),
            ],
        ),
        migrations.CreateModel(
            name='ContactGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_title', models.CharField(max_length=40, verbose_name='General Title')),
                ('general_subtitle', models.CharField(max_length=50, verbose_name='General Subtitle')),
                ('title', models.CharField(max_length=50, verbose_name='Content Title')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Subtitle')),
                ('text', models.TextField(verbose_name='Text')),
                ('inp1', models.CharField(max_length=50, verbose_name='Placeholder 1')),
                ('inp2', models.CharField(max_length=50, verbose_name='Placeholder 2')),
                ('inp3', models.CharField(max_length=50, verbose_name='Placeholder 3')),
                ('inp4', models.CharField(max_length=50, verbose_name='Placeholder 4')),
                ('inp5', models.CharField(max_length=50, verbose_name='Placeholder 5')),
                ('btn_name', models.CharField(max_length=50, verbose_name='Button Name')),
            ],
            options={
                'verbose_name': 'Contact GET',
                'verbose_name_plural': 'Contact GET',
            },
        ),
        migrations.CreateModel(
            name='ContactPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Username')),
                ('user_surname', models.CharField(max_length=50, verbose_name='Surname')),
                ('user_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact POST',
                'verbose_name_plural': 'Contact POST',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Copyright')),
                ('name', models.CharField(max_length=50, verbose_name='Designer Name')),
                ('name_link', models.URLField(verbose_name='Designer Name Link')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Logo Image')),
                ('path1', models.CharField(max_length=50, verbose_name='Path 1')),
                ('path2', models.CharField(max_length=50, verbose_name='Path 2')),
                ('path3', models.CharField(max_length=50, verbose_name='Path 3')),
                ('path4', models.CharField(max_length=50, verbose_name='Path 4')),
                ('path5', models.CharField(max_length=50, verbose_name='Path 5')),
                ('path6', models.CharField(max_length=50, verbose_name='Path 6')),
                ('path7', models.CharField(max_length=50, verbose_name='Path 7')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Header',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
                ('text', models.TextField(verbose_name='Text')),
                ('btn_name', models.CharField(max_length=30, verbose_name='Button Name')),
                ('price', models.CharField(max_length=10, verbose_name='Price')),
                ('procent', models.CharField(max_length=10, verbose_name='Procent')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageLastGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50, verbose_name='Title 1')),
                ('subtitle1', models.CharField(max_length=60, verbose_name='Subtitle 1')),
                ('colored_word1', models.CharField(max_length=40, verbose_name='Colored Word 1')),
                ('text', models.TextField(verbose_name='Text')),
                ('btn_name1', models.CharField(max_length=40, verbose_name='Button Name 1')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title2', models.CharField(max_length=50, verbose_name='Title 2')),
                ('subtitle2', models.CharField(max_length=60, verbose_name='Subtitle 2')),
                ('colored_word2', models.CharField(max_length=40, verbose_name='Colored Word 2')),
                ('btn_name2', models.CharField(max_length=40, verbose_name='Button Name 2')),
            ],
            options={
                'verbose_name': 'Home Page Last GET',
                'verbose_name_plural': 'Home Page Last GET',
            },
        ),
        migrations.CreateModel(
            name='HomePageLastPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, verbose_name='User Email')),
            ],
            options={
                'verbose_name': 'Home Page Last POST',
                'verbose_name_plural': 'Home Page Last POST',
            },
        ),
        migrations.CreateModel(
            name='ProductDetailInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_btn', models.CharField(max_length=40, verbose_name='Cart Button')),
                ('wish_btn', models.CharField(max_length=40, verbose_name='WishList Button')),
                ('subtitle1', models.CharField(max_length=50, verbose_name='Subtitle 1')),
                ('subtitle2', models.CharField(max_length=50, verbose_name='Subtitle 2')),
                ('title1', models.CharField(max_length=50, verbose_name='Title 1')),
                ('title2', models.CharField(max_length=50, verbose_name='Title 2')),
                ('subtitle3', models.CharField(max_length=50, verbose_name='Subtitle 3')),
                ('subtitle4', models.CharField(max_length=50, verbose_name='Subtitle 4')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
            ],
        ),
        migrations.CreateModel(
            name='ShopContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('price', models.CharField(max_length=10, verbose_name='Price')),
                ('new_price', models.CharField(blank=True, max_length=10, verbose_name='New Price')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('to_check', models.BooleanField(blank=True, verbose_name='For New Price')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('text', models.TextField(verbose_name='About Game')),
                ('tags', models.CharField(max_length=50, verbose_name='Game Tags')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ShopContentGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='Genre')),
                ('tag', models.CharField(max_length=30, verbose_name='Filter Tag')),
            ],
        ),
        migrations.CreateModel(
            name='ShopTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
            ],
            options={
                'verbose_name': 'Shop Title',
                'verbose_name_plural': 'Shop Title',
            },
        ),
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle1', models.CharField(max_length=50, verbose_name='Subtitle 1')),
                ('subtitle2', models.CharField(max_length=50, verbose_name='Subtitle 2')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
                ('text', models.TextField(verbose_name='Text')),
                ('link_name', models.CharField(max_length=50, verbose_name='Link Name')),
            ],
            options={
                'verbose_name': 'Sign In',
                'verbose_name_plural': 'Sign In',
            },
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle1', models.CharField(max_length=50, verbose_name='Subtitle 1')),
                ('subtitle2', models.CharField(max_length=50, verbose_name='Subtitle 2')),
                ('subtitle3', models.CharField(max_length=50, verbose_name='Subtitle 3')),
                ('subtitle4', models.CharField(max_length=50, verbose_name='Subtitle 4')),
                ('subtitle5', models.CharField(max_length=50, verbose_name='Subtitle 5')),
                ('subtitle6', models.CharField(max_length=50, verbose_name='Subtitle 6')),
                ('btn_name', models.CharField(max_length=40, verbose_name='Button Name')),
                ('text', models.TextField(verbose_name='Text')),
                ('link_name', models.CharField(max_length=50, verbose_name='Link Name')),
            ],
            options={
                'verbose_name': 'Sign Up',
                'verbose_name_plural': 'Sign Up',
            },
        ),
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
            ],
            options={
                'verbose_name': 'TopCategory',
                'verbose_name_plural': 'TopCategories',
            },
        ),
        migrations.CreateModel(
            name='TopCategoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='Genre')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='TopGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
                ('btn_name1', models.CharField(max_length=30, verbose_name='Button Name 1')),
                ('btn_name2', models.CharField(max_length=30, verbose_name='Button Name 2')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('subtitle', models.CharField(max_length=60, verbose_name='Subtitle')),
                ('btn_name', models.CharField(max_length=30, verbose_name='Button Name')),
                ('icon', models.CharField(max_length=50, verbose_name='Icon')),
            ],
        ),
        migrations.CreateModel(
            name='Verific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images', verbose_name='Image')),
                ('title1', models.CharField(max_length=100, verbose_name='Title 1')),
                ('title2', models.CharField(max_length=100, verbose_name='Title 2')),
                ('text', models.TextField(verbose_name='Text')),
            ],
            options={
                'verbose_name': 'Verific',
                'verbose_name_plural': 'Verific',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50, verbose_name='Title 1')),
                ('title2', models.CharField(max_length=50, verbose_name='Title 2')),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_items', to='main.shopcontent')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlistitems', to='main.wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingGameContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trending_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shopcontent')),
            ],
        ),
        migrations.CreateModel(
            name='TopGameContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_games', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shopcontent')),
            ],
        ),
        migrations.AddField(
            model_name='shopcontent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_prod', to='main.shopcontentgenre'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField(verbose_name='User Text')),
                ('review_date', models.DateField(auto_now=True, verbose_name='Review Date')),
                ('to_check', models.BooleanField(verbose_name='Accept / Reject')),
                ('user_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.shopcontent')),
                ('user_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count1', models.PositiveIntegerField(blank=True, verbose_name='Count')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='main.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.shopcontent')),
            ],
        ),
    ]
