# Generated by Django 4.2.1 on 2023-05-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ordered Username')),
                ('game', models.CharField(max_length=50, verbose_name='Ordered Game')),
                ('count', models.PositiveIntegerField(verbose_name='Ordered Game Count')),
                ('date', models.DateField(auto_now=True, verbose_name='Ordered Game Date')),
            ],
        ),
    ]
