# Generated by Django 4.2.1 on 2023-05-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_cartinfo_btn_name_cartinfo_btn_name1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForGuestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Text')),
                ('btn_name1', models.CharField(max_length=40, verbose_name='Button Name 1')),
                ('btn_name2', models.CharField(max_length=40, verbose_name='Button Name 2')),
            ],
        ),
        migrations.AddField(
            model_name='productdetailinfo',
            name='review_btn',
            field=models.CharField(default=1, max_length=40, verbose_name='Review Button Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='rule1',
            field=models.CharField(default=1, max_length=100, verbose_name='Rule 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='rule2',
            field=models.CharField(default=1, max_length=100, verbose_name='Rule 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='rule3',
            field=models.CharField(default=1, max_length=100, verbose_name='Rule 3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='rule4',
            field=models.CharField(default=1, max_length=100, verbose_name='Rule 4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signup',
            name='rule5',
            field=models.CharField(default=1, max_length=100, verbose_name='Rule 5'),
            preserve_default=False,
        ),
    ]
