# Generated by Django 4.2.1 on 2023-05-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_forguestuser_productdetailinfo_review_btn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistinfo',
            name='cart_btn',
            field=models.CharField(default=1, max_length=40, verbose_name='Cart Button'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlistinfo',
            name='del_btn',
            field=models.CharField(default=1, max_length=40, verbose_name='Delete Button'),
            preserve_default=False,
        ),
    ]
